TEXDIR /texlive
TEXMFSYSVAR /texlive/texmf-var
TEXMFSYSCONFIG /texlive/texmf-config
TEXMFLOCAL /texlive/texmf-local
TEXMFHOME $TEXMFLOCAL
TEXMFVAR $TEXMFSYSVAR
TEXMFCONFIG $TEXMFSYSCONFIG
collection-basic 1
collection-latex 1
option_autobackup 0
option_doc 0
option_src 0
portable 1
